import {    
    star,
    popular,
    calendary,
    action,
    adventure,
    animation,
    comedy,
    crime,
    documentary,
    drama,
    family,
    fantasy,
    history,
    horror,
    music,
    mystery,
    romance,
    science,
    thriller,
    tv,
    war,
    western} from '../assets'

export const categorys = [
    {id:1, name: "Top Rated",icon: popular},
    {id:2, name: "Polupar",icon: star},
    {id:3, name: "Upcoming",icon: calendary},
];

export const geners = [
    {id:4, name: "Action",icon: action},
    {id:5, name: "Adventure",icon: adventure},
    {id:6, name: "Animation",icon: animation},
    {id:7, name: "Comedy",icon: comedy},
    {id:8, name: "Crime",icon: crime},
    {id:9, name: "Documentary",icon: documentary},
    {id:10, name: "Drama",icon: drama},
    {id:11, name: "Family",icon: family},
    {id:12, name: "Fantasy",icon: fantasy},
    {id:13, name: "History",icon: history},
    {id:14, name: "Horror",icon: horror},
    {id:15, name: "Music",icon: music},
    {id:16, name: "Mystery",icon: mystery},
    {id:17, name: "Romance",icon: romance},
    {id:18, name: "Science Fiction",icon: science},
    {id:19, name: "TV Movie",icon: tv},
    {id:20, name: "Thriller",icon: thriller},
    {id:21, name: "War",icon: war},
    {id:22, name: "Western",icon: western}
]
